name: islamy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # المكتبات الأساسية
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  introduction_screen: ^4.0.0
  google_fonts: ^7.1.0
  
  # مكتبات إدارة الحالة والتخزين
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # مكتبة عرض الشرائح
  carousel_slider_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# الإعدادات المعدلة للأيقونة لتظهر بشكل كامل ومظبوط
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


  adaptive_icon_background: "#1C1C1C"
  adaptive_icon_foreground: "assets/images/app_icon.png"

  remove_alpha_channel_ios: true

flutter_native_splash:
  color: "#1C1C1C"
  image: "assets/images/app_icon.png"
  android_12:
    image: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/El_Messiri/
    - assets/files/Suras/
    - assets/files/Hadeeth/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/images/El_Messiri/ElMessiri-VariableFont_wght.ttf